# Generated by Django 5.1.1 on 2025-09-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_customuser_is_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills'),
        ),
    ]
