# Generated by Django 5.1.1 on 2025-09-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_created_at_job_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this job posting'),
        ),
    ]
