# Generated by Django 5.1.1 on 2025-09-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employer', 'Employer'), ('jobseeker', 'Job Seeker')], default='jobseeker', max_length=20),
        ),
    ]
